# Generated by Django 5.0.2 on 2024-02-26 12:33

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('manga_type', models.CharField(choices=[('manhwa', 'Manhwa'), ('manga', 'Manga'), ('manhua', 'Manhua'), ('comic', 'Comic'), ('other', 'Other')], default='other', max_length=30)),
                ('description', ckeditor.fields.RichTextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest', models.BooleanField(default=False)),
                ('treanding', models.BooleanField(default=False)),
                ('chapter_source', models.CharField(choices=[('manhwaz', 'Manhwaz'), ('other', 'Other')], default='other', max_length=50)),
                ('chapter_url', models.URLField(unique=True)),
                ('is_live', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangachapter', to='manga.manga')),
            ],
        ),
        migrations.CreateModel(
            name='TitleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(unique=True)),
                ('image_source', models.CharField(choices=[('manhwaz', 'Manhwaz'), ('other', 'Other')], default='other', max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangaimage', to='manga.manga')),
            ],
        ),
    ]
