# Generated by Django 5.0.3 on 2024-03-15 14:38

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MangaList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('manga_url', models.URLField(unique=True)),
                ('manga_type', models.CharField(choices=[('manhwa', 'Manhwa'), ('manga', 'Manga'), ('manhua', 'Manhua'), ('comic', 'Comic'), ('other', 'Other')], default='other', max_length=30)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChapterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_no', models.IntegerField(blank=True, null=True)),
                ('chapter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('volume_no', models.PositiveSmallIntegerField(default=1)),
                ('latest', models.BooleanField(default=False)),
                ('treanding', models.BooleanField(default=False)),
                ('chapter_source', models.CharField(choices=[('manhwaz', 'Manhwaz'), ('mangakakalot', 'Mangakakalot'), ('other', 'Other')], default='other', max_length=50)),
                ('chapter_url', models.URLField(unique=True)),
                ('is_live', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangachapter', to='manga.mangalist')),
            ],
        ),
        migrations.CreateModel(
            name='TitleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(unique=True)),
                ('image_source', models.CharField(choices=[('manhwaz', 'Manhwaz'), ('mangakakalot', 'Mangakakalot'), ('other', 'Other')], default='other', max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mangaimage', to='manga.mangalist')),
            ],
        ),
    ]
