# Generated by Django 5.0.2 on 2024-02-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='manga_url',
            field=models.URLField(default='', unique=True),
            preserve_default=False,
        ),
    ]
