# Generated by Django 5.0.3 on 2024-03-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterlist',
            name='chapter_source',
            field=models.CharField(choices=[('bato', 'Bato'), ('manhwaz', 'Manhwaz'), ('mangakakalot', 'Mangakakalot'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='titleimage',
            name='image_source',
            field=models.CharField(choices=[('bato', 'Bato'), ('manhwaz', 'Manhwaz'), ('mangakakalot', 'Mangakakalot'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
