# Generated by Django 5.0.2 on 2024-03-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_chapter_chapter_no_manga_manga_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chapter',
            new_name='ChapterList',
        ),
        migrations.RenameModel(
            old_name='Manga',
            new_name='MangaList',
        ),
    ]
