# Generated by Django 5.0.3 on 2024-03-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_alter_chapterlist_chapter_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterlist',
            name='latest',
        ),
        migrations.RemoveField(
            model_name='chapterlist',
            name='treanding',
        ),
        migrations.AddField(
            model_name='mangalist',
            name='latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mangalist',
            name='manga_rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mangalist',
            name='treanding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mangalist',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
