# Generated by Django 5.0.2 on 2024-03-06 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_rename_chapter_chapterlist_rename_manga_mangalist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titleimage',
            name='manga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mangaimage', to='manga.mangalist'),
        ),
    ]
