# Generated by Django 5.0.2 on 2024-03-07 07:18

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_alter_titleimage_manga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangalist',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
