# Generated by Django 5.0.2 on 2024-03-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_alter_mangalist_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titleimage',
            name='manga',
        ),
    ]
