# Generated by Django 5.0.2 on 2024-03-07 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_remove_titleimage_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='titleimage',
            name='manga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mangaimage', to='manga.mangalist'),
        ),
        migrations.AlterField(
            model_name='chapterlist',
            name='chapter_source',
            field=models.CharField(choices=[('manhwaz', 'Manhwaz'), ('mangakakalot', 'Mangakakalot'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='titleimage',
            name='image_source',
            field=models.CharField(choices=[('manhwaz', 'Manhwaz'), ('mangakakalot', 'Mangakakalot'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
