# Generated by Django 5.0.2 on 2024-03-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0007_titleimage_manga_alter_chapterlist_chapter_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titleimage',
            name='manga',
        ),
    ]
