# Generated by Django 5.0.2 on 2024-03-07 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0008_remove_titleimage_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='titleimage',
            name='manga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mangaimage', to='manga.mangalist'),
        ),
    ]
