# Generated by Django 5.0.2 on 2024-03-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0009_titleimage_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterlist',
            name='chapter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chapterlist',
            name='chapter_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
