# Generated by Django 5.0.2 on 2024-03-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0010_chapterlist_chapter_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterlist',
            name='volume_no',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
