# Generated by Django 5.0.2 on 2024-03-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0011_chapterlist_volume_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterlist',
            name='chapter_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
