# Generated by Django 5.0.9 on 2024-09-21 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Harvester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=25)),
                ('domain_url', models.URLField()),
                ('harvest_type', models.CharField(choices=[('manga', 'Manga'), ('anime', 'Anime'), ('none', 'None')], default='none', max_length=15)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingHarvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_scrape', models.DateTimeField()),
                ('last_scrape', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('harvest', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='harvesters.harvester')),
            ],
        ),
    ]
