# Generated by Django 5.0.9 on 2024-11-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest_routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingharvest',
            name='manga_url',
        ),
        migrations.AlterField(
            model_name='scrapingharvest',
            name='chapter_title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='scrapingharvest',
            name='chapter_url',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='scrapingharvest',
            name='manga_cover_img',
            field=models.CharField(max_length=250),
        ),
    ]
