# Generated by Django 5.0.9 on 2024-09-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvester',
            name='harvest_type',
            field=models.CharField(choices=[('manga', 'Manga'), ('anime', 'Anime'), ('both', 'Both'), ('none', 'None')], default='none', max_length=15),
        ),
    ]
