# Generated by Django 5.0.9 on 2024-10-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesters', '0002_alter_harvester_harvest_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingharvest',
            name='last_scrape',
        ),
        migrations.RemoveField(
            model_name='scrapingharvest',
            name='next_scrape',
        ),
        migrations.AddField(
            model_name='scrapingharvest',
            name='chapter_list',
            field=models.TextField(default=list),
        ),
        migrations.AddField(
            model_name='scrapingharvest',
            name='chapter_title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapingharvest',
            name='chapter_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapingharvest',
            name='manga_cover_img',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapingharvest',
            name='manga_list',
            field=models.TextField(default=list),
        ),
        migrations.AddField(
            model_name='scrapingharvest',
            name='manga_title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapingharvest',
            name='manga_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
