# Generated by Django 5.0.9 on 2024-11-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest_routes', '0002_remove_scrapingharvest_manga_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingharvest',
            name='manga_url',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
