# Generated by Django 5.0.9 on 2024-11-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest_routes', '0003_scrapingharvest_manga_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingharvest',
            name='payload',
            field=models.TextField(default=dict),
        ),
    ]
