# Generated by Django 5.0.9 on 2024-11-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest_routes', '0004_scrapingharvest_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingharvest',
            name='re_chapter_title',
            field=models.TextField(default=dict),
        ),
        migrations.AddField(
            model_name='scrapingharvest',
            name='re_chapter_url',
            field=models.TextField(default=dict),
        ),
        migrations.AddField(
            model_name='scrapingharvest',
            name='re_cover_img',
            field=models.TextField(default=dict),
        ),
        migrations.AddField(
            model_name='scrapingharvest',
            name='re_title',
            field=models.TextField(default=dict),
        ),
        migrations.AddField(
            model_name='scrapingharvest',
            name='re_url',
            field=models.TextField(default=dict),
        ),
    ]
