# Generated by Django 5.0.9 on 2024-11-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest_routes', '0005_scrapingharvest_re_chapter_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingharvest',
            name='manga_genre',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapingharvest',
            name='manga_genre_list',
            field=models.TextField(default=dict),
        ),
        migrations.AlterField(
            model_name='scrapingharvest',
            name='manga_list',
            field=models.TextField(default=dict),
        ),
    ]
