# Generated by Django 5.0.9 on 2024-11-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest_routes', '0006_scrapingharvest_manga_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingharvest',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapingharvest',
            name='description_list',
            field=models.TextField(default=dict),
        ),
    ]
