# Generated by Django 5.0.9 on 2024-11-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest_routes', '0007_scrapingharvest_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingharvest',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
