# Generated by Django 5.0.9 on 2024-11-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest_routes', '0009_chapterslogs_mangaslogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingharvest',
            name='description_list',
        ),
        migrations.RemoveField(
            model_name='scrapingharvest',
            name='manga_genre_list',
        ),
        migrations.RemoveField(
            model_name='scrapingharvest',
            name='re_chapter_title',
        ),
        migrations.RemoveField(
            model_name='scrapingharvest',
            name='re_chapter_url',
        ),
        migrations.RemoveField(
            model_name='scrapingharvest',
            name='re_cover_img',
        ),
        migrations.RemoveField(
            model_name='scrapingharvest',
            name='re_title',
        ),
        migrations.RemoveField(
            model_name='scrapingharvest',
            name='re_url',
        ),
        migrations.AddField(
            model_name='scrapingharvest',
            name='chapter_content',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapingharvest',
            name='chapter_payload',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapingharvest',
            name='manga_payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='scrapingharvest',
            name='chapter_list',
            field=models.JSONField(default=dict),
        ),
    ]
