# Generated by Django 5.0.9 on 2024-11-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest_routes', '0010_remove_scrapingharvest_description_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingharvest',
            name='chapter_payload',
            field=models.JSONField(default=dict),
        ),
    ]
