services:
  docs:
    image: manga_lab_local_docs
    container_name: manga_lab_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./manga_lab:/app/manga_lab:z
    ports:
      - '9000:9000'
    command: /start-docs
