# Generated by Django 5.0.3 on 2024-04-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangalab_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
