# Generated by Django 5.0.9 on 2024-11-08 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('harvest_routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField(blank=True)),
                ('related_to', models.CharField(choices=[('manga', 'Manga'), ('anime', 'Anime'), ('both', 'Both'), ('none', 'None')], default='none', max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MangaVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cover_img', models.URLField(unique=True)),
                ('description', models.TextField()),
                ('vault_url', models.URLField(unique=True)),
                ('category', models.CharField(choices=[('Manga', 'Manga'), ('Manhwa', 'Manhwa'), ('Manhua', 'Manhua'), ('Comics', 'Comics'), ('none', 'None')], default='Manga', max_length=10)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('none', 'None')], default='none', max_length=10)),
                ('is_new', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='manga_source', to='harvest_routes.harvester')),
            ],
        ),
        migrations.CreateModel(
            name='MangaChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(max_length=100)),
                ('chapter_url', models.URLField(unique=True)),
                ('chapter_number', models.PositiveSmallIntegerField()),
                ('is_new', models.BooleanField(default=False)),
                ('is_latest', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_chapter', to='mangavault.mangavault')),
            ],
        ),
    ]
