# Generated by Django 5.0.9 on 2024-11-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangavault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangavault',
            name='manga_title',
            field=models.TextField(default=str),
        ),
    ]
