# Generated by Django 5.0.9 on 2024-11-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangavault', '0003_alter_mangavault_manga_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangavault',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
