# Generated by Django 5.0.9 on 2024-11-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangavault', '0004_alter_mangavault_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangavault',
            name='cover_img',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mangavault',
            name='manga_title',
            field=models.TextField(blank=True),
        ),
    ]
