# Generated by Django 5.0.9 on 2024-11-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangavault', '0007_alter_mangavault_cover_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangavault',
            name='genre',
            field=models.ManyToManyField(related_name='manga_genre', to='mangavault.mangagenre'),
        ),
        migrations.AlterField(
            model_name='mangavault',
            name='cover_img',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mangavault',
            name='vault_url',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
