# Generated by Django 5.0.9 on 2024-11-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangavault', '0008_mangavault_genre_alter_mangavault_cover_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangachapter',
            name='chapter_list',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
