# Generated by Django 5.0.9 on 2024-11-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangavault', '0009_mangachapter_chapter_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangachapter',
            name='chapter_description',
            field=models.TextField(default=list),
        ),
    ]
