# Generated by Django 5.0.9 on 2024-11-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangavault', '0010_mangachapter_chapter_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangachapter',
            name='chapter_list',
            field=models.TextField(default=list),
        ),
    ]
