from urllib.parse import urlunparse
from mangalab.settings.components.get_env import (
    CELERY_BACKEND, CELERY_BROKER, RABBITMQ_DEFAULT_PASS, RABBITMQ_DEFAULT_USER,
    RABBITMQ_DEFAULT_VHOST, RABBITMQ_PORT, RABBITMQ_SERVICE)

if RABBITMQ_SERVICE == '' or RABBITMQ_SERVICE is None:
    RABBITMQ_SERVICE = 'instaastro-rabbitmq'
if RABBITMQ_PORT == '' or RABBITMQ_PORT is None:
    RABBITMQ_PORT = 5672

CELERY_BROKER_URL = urlunparse((
    'amqp',
    f"{RABBITMQ_DEFAULT_USER}:{RABBITMQ_DEFAULT_PASS}@{RABBITMQ_SERVICE}:{RABBITMQ_PORT}",
    RABBITMQ_DEFAULT_VHOST,
    '', '', ''
))
CELERY_RESULT_BACKEND = CELERY_BACKEND
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_BROKER_CONNECTION_TIMEOUT = 30
CELERY_BROKER_HEARTBEAT = None
CELERY_BROKER_POOL_LIMIT = None
CELERY_TIMEZONE = 'Asia/Calcutta'